/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as FinanceRouteImport } from './routes/finance'
import { Route as SwimmerRouteImport } from './routes/swimmer'
import { Route as SwimmersNewRouteImport } from './routes/swimmers.new'
import { Route as PrintTypeIdRouteImport } from './routes/print.$type.$id'
import { Route as SwimmersIdIndexRouteImport } from './routes/swimmers.$id.index'
import { Route as SwimmersIdEditRouteImport } from './routes/swimmers.$id.edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceRoute = FinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => rootRouteImport,
} as any)
const SwimmerRoute = SwimmerRouteImport.update({
  id: '/swimmer',
  path: '/swimmer',
  getParentRoute: () => rootRouteImport,
} as any)
const SwimmersNewRoute = SwimmersNewRouteImport.update({
  id: '/swimmers/new',
  path: '/swimmers/new',
  getParentRoute: () => rootRouteImport,
} as any)
const PrintTypeIdRoute = PrintTypeIdRouteImport.update({
  id: '/print/$type/$id',
  path: '/print/$type/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const SwimmersIdIndexRoute = SwimmersIdIndexRouteImport.update({
  id: '/swimmers/$id/',
  path: '/swimmers/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const SwimmersIdEditRoute = SwimmersIdEditRouteImport.update({
  id: '/swimmers/$id/edit',
  path: '/swimmers/$id/edit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/finance': typeof FinanceRoute
  '/swimmer': typeof SwimmerRoute
  '/swimmers/new': typeof SwimmersNewRoute
  '/print/$type/$id': typeof PrintTypeIdRoute
  '/swimmers/$id/edit': typeof SwimmersIdEditRoute
  '/swimmers/$id/': typeof SwimmersIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/finance': typeof FinanceRoute
  '/swimmer': typeof SwimmerRoute
  '/swimmers/new': typeof SwimmersNewRoute
  '/print/$type/$id': typeof PrintTypeIdRoute
  '/swimmers/$id/edit': typeof SwimmersIdEditRoute
  '/swimmers/$id': typeof SwimmersIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/finance': typeof FinanceRoute
  '/swimmer': typeof SwimmerRoute
  '/swimmers/new': typeof SwimmersNewRoute
  '/print/$type/$id': typeof PrintTypeIdRoute
  '/swimmers/$id/edit': typeof SwimmersIdEditRoute
  '/swimmers/$id/': typeof SwimmersIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/finance'
    | '/swimmer'
    | '/swimmers/new'
    | '/print/$type/$id'
    | '/swimmers/$id/edit'
    | '/swimmers/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/finance'
    | '/swimmer'
    | '/swimmers/new'
    | '/print/$type/$id'
    | '/swimmers/$id/edit'
    | '/swimmers/$id'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/finance'
    | '/swimmer'
    | '/swimmers/new'
    | '/print/$type/$id'
    | '/swimmers/$id/edit'
    | '/swimmers/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  FinanceRoute: typeof FinanceRoute
  SwimmerRoute: typeof SwimmerRoute
  SwimmersNewRoute: typeof SwimmersNewRoute
  PrintTypeIdRoute: typeof PrintTypeIdRoute
  SwimmersIdEditRoute: typeof SwimmersIdEditRoute
  SwimmersIdIndexRoute: typeof SwimmersIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance': {
      id: '/finance'
      path: '/finance'
      fullPath: '/finance'
      preLoaderRoute: typeof FinanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/swimmer': {
      id: '/swimmer'
      path: '/swimmer'
      fullPath: '/swimmer'
      preLoaderRoute: typeof SwimmerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/swimmers/new': {
      id: '/swimmers/new'
      path: '/swimmers/new'
      fullPath: '/swimmers/new'
      preLoaderRoute: typeof SwimmersNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/print/$type/$id': {
      id: '/print/$type/$id'
      path: '/print/$type/$id'
      fullPath: '/print/$type/$id'
      preLoaderRoute: typeof PrintTypeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/swimmers/$id/': {
      id: '/swimmers/$id/'
      path: '/swimmers/$id'
      fullPath: '/swimmers/$id/'
      preLoaderRoute: typeof SwimmersIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/swimmers/$id/edit': {
      id: '/swimmers/$id/edit'
      path: '/swimmers/$id/edit'
      fullPath: '/swimmers/$id/edit'
      preLoaderRoute: typeof SwimmersIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  FinanceRoute: FinanceRoute,
  SwimmerRoute: SwimmerRoute,
  SwimmersNewRoute: SwimmersNewRoute,
  PrintTypeIdRoute: PrintTypeIdRoute,
  SwimmersIdEditRoute: SwimmersIdEditRoute,
  SwimmersIdIndexRoute: SwimmersIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
