CREATE TABLE public.swimmers (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  name_ar text NOT NULL,
  name_fr text NOT NULL DEFAULT '',
  birth_date date NOT NULL,
  birth_place text NOT NULL DEFAULT '',
  gender text NOT NULL CHECK (gender IN ('male','female')),
  blood_type text NOT NULL DEFAULT '',
  father_name text NOT NULL DEFAULT '',
  father_phone text NOT NULL DEFAULT '',
  photo text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
GRANT SELECT, INSERT, UPDATE, DELETE ON public.swimmers TO authenticated;
GRANT ALL ON public.swimmers TO service_role;
ALTER TABLE public.swimmers ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Authenticated staff manage swimmers" ON public.swimmers FOR ALL TO authenticated USING (true) WITH CHECK (true);

CREATE TABLE public.payments (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  receipt_number bigint GENERATED BY DEFAULT AS IDENTITY (START WITH 1000),
  swimmer_id uuid NOT NULL REFERENCES public.swimmers(id) ON DELETE CASCADE,
  amount numeric(12,2) NOT NULL CHECK (amount >= 0),
  paid_at date NOT NULL,
  duration_months integer NOT NULL CHECK (duration_months IN (1,3,12)),
  method text NOT NULL CHECK (method IN ('cash','ccp','baridi')),
  receipt_image text,
  status text NOT NULL CHECK (status IN ('paid','unpaid','late')),
  expires_at date NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
GRANT SELECT, INSERT, UPDATE, DELETE ON public.payments TO authenticated;
GRANT ALL ON public.payments TO service_role;
GRANT USAGE, SELECT ON SEQUENCE public.payments_receipt_number_seq TO authenticated, service_role;
ALTER TABLE public.payments ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Authenticated staff manage payments" ON public.payments FOR ALL TO authenticated USING (true) WITH CHECK (true);

CREATE TABLE public.expenses (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  date date NOT NULL,
  reason text NOT NULL,
  amount numeric(12,2) NOT NULL CHECK (amount >= 0),
  note text NOT NULL DEFAULT '',
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
GRANT SELECT, INSERT, UPDATE, DELETE ON public.expenses TO authenticated;
GRANT ALL ON public.expenses TO service_role;
ALTER TABLE public.expenses ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Authenticated staff manage expenses" ON public.expenses FOR ALL TO authenticated USING (true) WITH CHECK (true);

CREATE OR REPLACE FUNCTION public.set_updated_at() RETURNS trigger LANGUAGE plpgsql SET search_path = public AS $$ BEGIN NEW.updated_at = now(); RETURN NEW; END; $$;
CREATE TRIGGER swimmers_updated_at BEFORE UPDATE ON public.swimmers FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();
CREATE TRIGGER payments_updated_at BEFORE UPDATE ON public.payments FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();
CREATE TRIGGER expenses_updated_at BEFORE UPDATE ON public.expenses FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

CREATE OR REPLACE FUNCTION public.get_public_swimmer_card(swimmer_uuid uuid)
RETURNS TABLE(id uuid, name_ar text, name_fr text, photo text, subscription_active boolean, expires_at date)
LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public
AS $$
  SELECT s.id, s.name_ar, s.name_fr, s.photo,
    COALESCE(p.status = 'paid' AND p.expires_at >= CURRENT_DATE, false) AS subscription_active,
    p.expires_at
  FROM public.swimmers s
  LEFT JOIN LATERAL (
    SELECT status, expires_at FROM public.payments
    WHERE swimmer_id = s.id ORDER BY paid_at DESC, created_at DESC LIMIT 1
  ) p ON true
  WHERE s.id = swimmer_uuid;
$$;
REVOKE ALL ON FUNCTION public.get_public_swimmer_card(uuid) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.get_public_swimmer_card(uuid) TO anon, authenticated, service_role;

CREATE INDEX payments_swimmer_latest_idx ON public.payments(swimmer_id, paid_at DESC, created_at DESC);
CREATE INDEX expenses_date_idx ON public.expenses(date DESC);